import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Card, CardContent, CardTitle } from "@/components/ui/card";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-screen h-screen flex justify-center items-center">
          <Card className="w-[500px] h-4/6 flex flex-col">
            <CardTitle className="text-6xl font-black text-center pt-8">SolaMint</CardTitle>
            <CardContent className="mt-6 w-full flex-grow">{children}</CardContent>
          </Card>
        </div>
      </body>
    </html>
  );
}
